### PR TITLE
Update metadata | Add Screenshots

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Many whitespace errors fixed automatically by the editor, do ignore them in the diff to get a clear view of the changes. Will be adding screenshots.

### CODE REVIEW

**Comment by quozl** [comment]
You've changed gui.py from GPL to LGPL?

**Comment by vipulgupta2048** [comment]
@quozl  Sorry for that. This might have occurred while replacing the license address. 
Also, added the screenshots.

**Comment by quozl** [comment]
You also changed GPL to LGPL in other files, it seems.  And removed blanks.  Could you please review the [aggregate change](https://github.com/sugarlabs/fifty-two-activity/pull/3/files) again to make sure it is what you want?  Remember to click on "Load diff", to expand the diffs.

**Comment by vipulgupta2048** [comment]
@quozl Fixed and reviewed other files as well.

**Pull request merged**
