### PR TITLE
Release V4

### LINKED ISSUE #6: Create Readme.

### LINKED ISSUE #7: Activity does not quit after pressing Stop button
I have tested the activity in Sugar with the GNOME desktop environment. To stop it, I had to manually kill the activity process.

This can be reproduce by
```
git clone https://github.com/sugarlabs/fifty-two-activity.git
cd fifty-two-activity
sugar-activity3 .
```

### PR DESCRIPTION
**Pull request by ghost**
- [x] Stop Button Working
- [x] Race Condition Handled
- [x] Readme Added
- [x] Pot File initiated
- [x] V4

Special Thanks to @JuiP
 
- [x] Handled camera not found
- [x] Handled Error Event Queue Full
- [x] Added .flake8

Kindly review @walterbender @chimosky @quozl .
For reference see the pr https://github.com/sugarlabs/fifty-two-activity/pull/5
Errors raised by @chimosky and @quozl  are addressed.

This close https://github.com/sugarlabs/fifty-two-activity/issues/7.
This close https://github.com/sugarlabs/fifty-two-activity/issues/6.

### CODE REVIEW

**Comment by ghost** [comment]
Also yes photo() plays a important role it helps in customising deck appearance.

**Comment by ghost** [comment]
- Handled the error event queue full, hopefully commit message provides with insight what actually is done there.
- Coming to camera not found, centered the message and guided the user to click on deck button instead to use photo from journal or some already inbuild photos in absence of camera.

**Comment by ghost** [comment]
Also I am sorry in advance, as I dont exactly know how some files like news etc are being edited so havent looked at them or how exactly version is changed, worked on this PR as all the issues can be solved.

**Review by chimosky — COMMENTED** [review]
Your commit message says _**Removed redundant `self.running` checks as in GUI interactions**_ but there's no removal of any check instead there's removal of assignments.

Also avoid using ticks in git commit messages as git doesn't do any markdown formatting, you can use that in GH comments.

**Comment by chimosky** [comment]
Reviewed 25213cf , not tested.

We have a maintainer [checklist](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#checklist---maintainer) you should go through if you haven't.

This doesn't close #2, I'll upload the activity to weblate after this is merged.

**Comment by ghost** [comment]
> Your commit message says _**Removed redundant `self.running` checks as in GUI interactions**_ but there's no removal of any check instead there's removal of assignments.
> 
> Also avoid using ticks in git commit messages as git doesn't do any markdown formatting, you can use that in GH comments.

Assignment:
- In the run() method's initialization, self.running is set to True to start the game loop.

Checks:
- The game loop runs while self.running is True.
- When the game should exit (e.g., on pygame.QUIT), self.running is set to False, stopping the loop.
- The code checks self.running to break out of the loop if it's False.
- So, self.running is used to control the loop's execution by assigning a value (True to start, False to stop) and checking it to determine whether to continue or exit the loop.

Well I am unsure on the part because I took the sense of whole loop though if you want can change that to assignments.

**Comment by ghost** [comment]
Yes changes the commit message , Thanks!!
Removed issue 2.

**Comment by ghost** [comment]
I guess then news can be updated later lets say when version 5 is launched with several other updates etc? @chimosky

**Comment by chimosky** [comment]
> I guess then news can be updated later lets say when version 5 is launched with several other updates etc? @chimosky

The news file is updated as part of the release because that's what tells you what changed in that particular release.

**Comment by ghost** [comment]
Branch seem to have conflicts, Closing Thanks.

**Pull request closed without merging**
